### ISSUE TITLE
CM3+ Flashing / Provisioning Does Not Seem to Work

### ISSUE THREAD

**Issue by stevenm3656** [raspberrypi/cmprovision#37]
Hello, hoping to get some help.

Perhaps I just haven't left it long enough, but not sure it should take more than a few hours.

Setup:

Provisioner:
Pi 4b 8GBram, 64GB micro SD with latest 64bit Raspberry Pi OS Lite (as of 31/01/2024 - yesterday)

Web interface working (over WiFi), images uploaded and projects set up.

Tried to provision / flash a CM3+ 32GB:

-  connected the Slave USB on the official IO Board to the Pi 4
- powered on CM3+
- from the logs it looks like this is detected as I can see the bootloader messages you would normally see from running rpiboot on windows etc

Pi doesn't appear to be flashed with image.

Balena etcher would take around 16 minutes to flash this image, what should I expect from this?
Is there any steps for CM3+ not listed on this repo? Can't find much online.
Is there any other logs that would show anything after the bootloader stuff?

Many thanks,

Steven

**Comment by maxnet** [comment]
If it is a recent RPI OS version you may need to swap out networkmanager for dhcpcd (via sudo raspi-config).

Other than that connect HDMI to the boards you are provisioning and check screen for errors.

**Comment by stevenm3656** [comment]
Thanks,

No option for selecting between networkmanager or dhcpcd on the Pi 4.

Connected HDMI to CM3+, got:

... random: fast init done
curl: (7) Failed to connect to ... port 80: Connection timed out

Welcome to Buildroot
scriptexecute login:

**Comment by maxnet** [comment]
>No option for selecting between networkmanager or dhcpcd on the Pi 4.


Easiest solution may be to install an older RPI OS version (Bullseye) that does still have that option.



Otherwise you would need to figure out how you can DISABLE IPv6 privacy extensions on NetworkManager instead. 
The catch do is that it must be set globally, because every time a new module is being provisioned the usb network adapter will change. So network manager per connection profile settings are not going to do. And I don't know whether or not the version of NetworkManager RPI OS ships supports the option to set it globally...

The utility software that is being booted on the modules being provisioned expects that it is able to reach the server on a predictable IPv6 link local address, that can be calculated based on the MAC address of the USB network adapter (EUI-64 method).
And if NetworkManager is randomizing the IPv6 address of the server for privacy reasons instead, the module has no clue what IPv6 it needs to connect to...

This is only an issue with older modules like CM3 that are provisioned through USB.
Use CM4 if you can...

**Comment by stevenm3656** [comment]
Thanks Max,

You pointed me in the right direction, all sorted now and the provisioner is excellent, thanks a lot to all who worked on it.

I'll detail the fix for anyone else facing the same issue.

I was able to stay on the latest version and follow instructions from [here](https://forums.raspberrypi.com/viewtopic.php?t=360586), I'll also add the steps below for completeness.

I then had to edit `/etc/dhcpcd.conf` as per the instructions on the [Provisioning from an alternate OS section.](https://github.com/raspberrypi/cmprovision#provisioning-from-an-alternate-os), I'll include this in the steps below.

1. `sudo systemctl disable NetworkManager`
2. `sudo systemctl stop NetworkManager`
3. `sudo apt-get update`
4. `sudo apt-get install -y dhcpcd5`
5. `sudo cp /usr/share/dhcpcd/hooks/10-wpa_supplicant /lib/dhcpcd/dhcpcd-hooks/10-wpa_supplicant`
6. `sudo nano /etc/wpa_supplicant/wpa_supplicant.conf`

Key in your wifi credential as usual

```
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
country=GB

network={
  ssid="<Enterprise-SSID>"
  key_mgmt=WPA-EAP
  eap=PEAP
  identity="<username>"
  password=hash:<hashed-password>
}
```

7. `sudo nano /etc/dhcpcd.conf`

At the bottom of the file un-comment `#slaac hwaddr` and comment `slaac private` so you have:

```
# Generate SLAAC address using the Hardware Address of the interface
slaac hwaddr
# OR generate Stable Private IPv6 Addresses based from the DUID
#slaac private
```

9. `sudo reboot`
